### ISSUE TITLE
apk already packaged?

### ISSUE THREAD

**Issue by 7fe** [thomasvidas/Simple-Lockscreen#1]
Is there an apk already packaged?

I would like to test this app to if its could be useful for a fork.

Lineage OS 14(Android 7.1) Nexus 5

**Comment by thomasvidas** [comment]
No sorry I don't have the APK anymore and I don't really do Android development anymore so I don't have any interest in making an updated version.  The Keyguard disable code was deprecated several versions ago so I don't know if that still works, but the intent/receiver code that launches the lockscreen activity doesn't seem to be deprecated so that should still work.

Feel free to fork this and make an app though, I didn't include a license, but this is MIT licensed.
